
CREATE TABLE source_product (
  id SERIAL PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  qty INT NOT NULL,
  selling_price DECIMAL NOT NULL,
  promo_price DECIMAL NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);